/**
 * GitHub Actions Workflow YAML Generator
 *
 * Generates a ready-to-use GitHub Actions workflow YAML
 * that scans the repo for cryptographic usage and uploads
 * a CycloneDX CBOM as an artifact.
 */
import type { WorkflowOptions } from './types';

export function generateWorkflowYaml(options: WorkflowOptions): string {
  const {
    language = 'java',
    branches = [options.branch || 'main'],
    triggers = ['push', 'pull_request'],
    artifactName = 'cbom-report',
    schedule,
    selfHostedRunner = false,
    runnerLabel = 'self-hosted, linux, x64',
    sonarEnabled = false,
    outputFormat = 'json',
    pqcThresholdEnabled = false,
    pqcThreshold = 80,
    excludePaths = [],
    retentionDays = 90,
    failOnError = true,
    uploadToRelease = false,
  } = options;

  // When sonar is enabled, default to self-hosted runner (SonarQube is typically internal)
  const useSelfHosted = sonarEnabled ? (options.selfHostedRunner !== undefined ? selfHostedRunner : true) : selfHostedRunner;

  const languages = sonarEnabled ? language.split(',').map((l: string) => l.trim()).filter(Boolean) : [];
  const isSarif = outputFormat === 'sarif';

  const branchList = branches.join(', ');

  // Build trigger block
  let onBlock = 'on:\n';
  if (triggers.includes('push')) {
    onBlock += `  push:\n    branches: [${branchList}]\n`;
    if (excludePaths.length > 0) {
      onBlock += `    paths-ignore:\n${excludePaths.map((p) => `      - '${p}'`).join('\n')}\n`;
    }
  }
  if (triggers.includes('pull_request')) {
    onBlock += `  pull_request:\n    branches: [${branchList}]\n`;
    if (excludePaths.length > 0) {
      onBlock += `    paths-ignore:\n${excludePaths.map((p) => `      - '${p}'`).join('\n')}\n`;
    }
  }
  if (triggers.includes('release')) {
    onBlock += `  release:\n    types: [published]\n`;
  }
  if (triggers.includes('schedule') || schedule) {
    onBlock += `  schedule:\n    - cron: '${schedule || '0 2 * * 1'}'\n`;
  }
  onBlock += `  workflow_dispatch:\n`;

  const runsOn = useSelfHosted ? `[${runnerLabel}]` : 'ubuntu-latest';

  // Permissions
  let permLines = `permissions:\n  contents: ${uploadToRelease ? 'write' : 'read'}`;
  if (isSarif) permLines += `\n  security-events: write`;

  // Build steps (only when sonar is enabled — compiled bytecode improves analysis)
  let buildSteps = '';
  if (sonarEnabled && languages.length > 0) {
    const steps = languages.map((lang: string) => getBuildStep(lang)).filter(Boolean);
    if (steps.length > 0) buildSteps = '\n\n' + steps.join('\n\n');
  }

  // Action inputs
  const withLines: string[] = [];
  withLines.push(`          scan-path: '.'`);
  withLines.push(`          output-format: '${outputFormat}'`);
  if (failOnError) withLines.push(`          fail-on-vulnerable: 'true'`);
  if (pqcThresholdEnabled) withLines.push(`          quantum-safe-threshold: '${pqcThreshold}'`);
  if (excludePaths.length > 0) withLines.push(`          exclude-patterns: '${excludePaths.join(',')}'`);
  if (sonarEnabled) {
    withLines.push(`          sonar-host-url: \${{ secrets.SONAR_HOST_URL }}`);
    withLines.push(`          sonar-token: \${{ secrets.SONAR_TOKEN }}`);
  }

  // SARIF upload step
  const sarifUpload = isSarif ? `
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: cbom.sarif
` : '';

  // Upload to release step
  const releaseStep = uploadToRelease ? `
      - name: Attach CBOM to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: cbom.json
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
` : '';

  return `# ──────────────────────────────────────────────────────────
# CBOM (Cryptographic Bill of Materials) Scanner
# Generated by QuantumGuard CBOM Hub
# ──────────────────────────────────────────────────────────
name: ${sonarEnabled ? 'CBOM Security Scan' : 'CBOM Scan'}

${onBlock}
${permLines}

jobs:
  cbom-scan:
    runs-on: ${runsOn}

    steps:
      - uses: actions/checkout@v4
${buildSteps}
      - name: Run QuantumGuard CBOM Scanner
        id: cbom
        uses: test-srm-digi/cbom-analyser@main
        with:
${withLines.join('\n')}

      - name: Upload CBOM Report${failOnError ? '' : '\n        if: always()'}
        uses: actions/upload-artifact@v4
        with:
          name: ${artifactName}
          path: cbom.json
          retention-days: ${retentionDays}
${sarifUpload}${releaseStep}`;
}

function getBuildStep(language: string): string {
  switch (language.toLowerCase()) {
    case 'java':
      return `      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build (compile only — no tests)
        run: |
          if [ -f "mvnw" ]; then ./mvnw compile -q -DskipTests
          elif [ -f "gradlew" ]; then ./gradlew classes -q
          elif [ -f "pom.xml" ]; then mvn compile -q -DskipTests
          else echo "No Java build tool detected"; fi`;

    case 'python':
      return `      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt 2>/dev/null || true`;

    case 'go':
    case 'golang':
      return `      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build project
        run: go build ./...`;

    default:
      return '';
  }
}
