// ══════════════════════════════════════════════════════════════
//  Discovery Module — Sample Data
//  Realistic data for all 5 integration-sourced tabs
// ══════════════════════════════════════════════════════════════

import type {
  DiscoveryCertificate,
  DiscoveryEndpoint,
  DiscoverySoftware,
  DiscoveryDevice,
  DiscoveryCbomImport,
} from './types';

/* ═══════════════════════════════════════════════════════════════
   1. Certificates — DigiCert Trust Lifecycle Manager
   ═══════════════════════════════════════════════════════════════ */

export const CERTIFICATES: DiscoveryCertificate[] = [
  { id: 'c1',  commonName: 'Production Web Portal',        caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-08-15', serialNumber: '0A:1B:2C:3D', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c2',  commonName: 'Database Server Primary',      caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-11-01', serialNumber: '1A:2B:3C:4D', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c3',  commonName: 'Payment Gateway',              caVendor: 'GlobalSign',  status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '4096 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-03-22', serialNumber: '2A:3B:4C:5D', signatureAlgorithm: 'SHA384withRSA' },
  { id: 'c4',  commonName: 'Quantum Safe Infrastructure',  caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'ML-DSA', keyLength: '65 bytes',  quantumSafe: true,  source: 'DigiCert TLM',  expiryDate: '2028-01-10', serialNumber: '3A:4B:5C:6D', signatureAlgorithm: 'ML-DSA-65' },
  { id: 'c5',  commonName: 'Quantum Ready Microservice',   caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'ML-DSA', keyLength: '65 bytes',  quantumSafe: true,  source: 'DigiCert TLM',  expiryDate: '2028-06-15', serialNumber: '4A:5B:6C:7D', signatureAlgorithm: 'ML-DSA-65' },
  { id: 'c6',  commonName: 'Mail Server Exchange',         caVendor: 'Sectigo',     status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-05-30', serialNumber: '5A:6B:7C:8D', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c7',  commonName: 'VPN Gateway Corporate',        caVendor: 'Self-signed', status: 'Issued',  keyAlgorithm: 'ECDSA',  keyLength: 'P-384',     quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-12-01', serialNumber: '6A:7B:8C:9D', signatureAlgorithm: 'SHA384withECDSA' },
  { id: 'c8',  commonName: 'File Storage Server',          caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-09-20', serialNumber: '7A:8B:9C:AD', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c9',  commonName: 'Monitoring Platform',          caVendor: 'GlobalSign',  status: 'Expired', keyAlgorithm: 'ECDSA',  keyLength: 'P-256',     quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2025-12-01', serialNumber: '8A:9B:AC:BD', signatureAlgorithm: 'SHA256withECDSA' },
  { id: 'c10', commonName: 'Logging Service',              caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '3072 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-07-14', serialNumber: '9A:AB:BC:CD', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c11', commonName: 'API Gateway Primary',          caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-10-05', serialNumber: 'AA:BB:CC:DD', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c12', commonName: 'CI/CD Pipeline Runner',        caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-08-28', serialNumber: 'AB:BC:CD:DE', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c13', commonName: 'Internal SSO Provider',        caVendor: 'DigiCert',    status: 'Revoked', keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-04-12', serialNumber: 'AC:BD:CE:DF', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c14', commonName: 'CDN Edge Node',                caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'ECDSA',  keyLength: 'P-256',     quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-01-18', serialNumber: 'AD:BE:CF:D0', signatureAlgorithm: 'SHA256withECDSA' },
  { id: 'c15', commonName: 'Backup Service',               caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-06-25', serialNumber: 'AE:BF:C0:D1', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c16', commonName: 'Container Registry',           caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-02-14', serialNumber: 'AF:C0:D1:E2', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c17', commonName: 'Message Queue Broker',         caVendor: 'GlobalSign',  status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-12-10', serialNumber: 'B0:C1:D2:E3', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c18', commonName: 'Load Balancer External',       caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '4096 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-09-30', serialNumber: 'B1:C2:D3:E4', signatureAlgorithm: 'SHA384withRSA' },
  { id: 'c19', commonName: 'PQC Gateway Service',          caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'ML-DSA', keyLength: '87 bytes',  quantumSafe: true,  source: 'DigiCert TLM',  expiryDate: '2028-12-01', serialNumber: 'B2:C3:D4:E5', signatureAlgorithm: 'ML-DSA-87' },
  { id: 'c20', commonName: 'LDAP Directory Server',        caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-07-22', serialNumber: 'B3:C4:D5:E6', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c21', commonName: 'Redis Cache Cluster',          caVendor: 'Sectigo',     status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-11-18', serialNumber: 'B4:C5:D6:E7', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c22', commonName: 'Elasticsearch Indexer',        caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-04-05', serialNumber: 'B5:C6:D7:E8', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c23', commonName: 'Notification Service',         caVendor: 'DigiCert',    status: 'Pending', keyAlgorithm: 'SLH-DSA', keyLength: '128f',     quantumSafe: true,  source: 'DigiCert TLM',  expiryDate: '2028-10-01', serialNumber: 'B6:C7:D8:E9', signatureAlgorithm: 'SLH-DSA-128f' },
  { id: 'c24', commonName: 'Analytics Pipeline',           caVendor: 'GlobalSign',  status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-09-12', serialNumber: 'B7:C8:D9:EA', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c25', commonName: 'Secrets Manager Vault',        caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '4096 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-06-20', serialNumber: 'B8:C9:DA:EB', signatureAlgorithm: 'SHA384withRSA' },
  { id: 'c26', commonName: 'Event Streaming Platform',     caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'ECDSA',  keyLength: 'P-256',     quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-03-15', serialNumber: 'B9:CA:DB:EC', signatureAlgorithm: 'SHA256withECDSA' },
  { id: 'c27', commonName: 'Data Warehouse Service',       caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-10-30', serialNumber: 'BA:CB:DC:ED', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c28', commonName: 'DNS Server Primary',           caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-01-05', serialNumber: 'BB:CC:DD:EE', signatureAlgorithm: 'SHA256withRSA' },
  { id: 'c29', commonName: 'Kubernetes API Server',        caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'ECDSA',  keyLength: 'P-384',     quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2027-08-18', serialNumber: 'BC:CD:DE:EF', signatureAlgorithm: 'SHA384withECDSA' },
  { id: 'c30', commonName: 'Compliance Dashboard',         caVendor: 'DigiCert',    status: 'Issued',  keyAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, source: 'DigiCert TLM',  expiryDate: '2026-12-22', serialNumber: 'BD:CE:DF:F0', signatureAlgorithm: 'SHA256withRSA' },
];

/* ═══════════════════════════════════════════════════════════════
   2. Endpoints — Network TLS Scanner
   ═══════════════════════════════════════════════════════════════ */

export const ENDPOINTS: DiscoveryEndpoint[] = [
  { id: 'e1',  hostname: 'loadbalancer-01.corp.local',      ipAddress: '10.0.0.1',       port: 443,  tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_256_GCM_SHA384',             keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:30:00Z', certCommonName: 'Load Balancer External' },
  { id: 'e2',  hostname: 'vpn-gateway-01.corp.local',       ipAddress: '10.0.0.2',       port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:30:00Z', certCommonName: 'VPN Gateway Corporate' },
  { id: 'e3',  hostname: 'proxy-01.corp.local',             ipAddress: '10.0.0.5',       port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_128_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:31:00Z' },
  { id: 'e4',  hostname: 'vault-01.corp.local',             ipAddress: '10.0.0.50',      port: 8200, tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_CHACHA20_POLY1305_SHA256',        keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:31:00Z', certCommonName: 'Secrets Manager Vault' },
  { id: 'e5',  hostname: 'database-01.corp.local',          ipAddress: '10.0.1.25',      port: 5432, tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_CBC',      keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:32:00Z', certCommonName: 'Database Server Primary' },
  { id: 'e6',  hostname: 'git-server-01.corp.local',        ipAddress: '10.10.3.40',     port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:32:00Z' },
  { id: 'e7',  hostname: 'cdn-edge-01.corp.local',          ipAddress: '10.20.1.101',    port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM',   keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:33:00Z', certCommonName: 'CDN Edge Node' },
  { id: 'e8',  hostname: 'backup-server-01.corp.local',     ipAddress: '10.30.5.75',     port: 443,  tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_128_GCM_SHA256',             keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:33:00Z' },
  { id: 'e9',  hostname: 'docker-registry-01.corp.local',   ipAddress: '10.40.2.15',     port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_128_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:34:00Z', certCommonName: 'Container Registry' },
  { id: 'e10', hostname: 'analytics-01.corp.local',         ipAddress: '10.50.1.25',     port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:34:00Z' },
  { id: 'e11', hostname: 'k8s-api-01.corp.local',           ipAddress: '10.60.1.10',     port: 6443, tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_256_GCM_SHA384',             keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:35:00Z', certCommonName: 'Kubernetes API Server' },
  { id: 'e12', hostname: 'mq-broker-01.corp.local',         ipAddress: '10.70.3.25',     port: 5671, tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_CBC',      keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:35:00Z' },
  { id: 'e13', hostname: 'pqc-gateway-01.corp.local',       ipAddress: '10.80.1.5',      port: 443,  tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_256_GCM_SHA384',             keyAgreement: 'ML-KEM-768',  quantumSafe: true,  source: 'Network Scanner', lastScanned: '2026-02-25T14:36:00Z', certCommonName: 'PQC Gateway Service' },
  { id: 'e14', hostname: 'pqc-service-01.corp.local',       ipAddress: '10.80.1.10',     port: 443,  tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_256_GCM_SHA384',             keyAgreement: 'ML-KEM-768',  quantumSafe: true,  source: 'Network Scanner', lastScanned: '2026-02-25T14:36:00Z' },
  { id: 'e15', hostname: 'pqc-infra-01.corp.local',         ipAddress: '10.80.1.15',     port: 443,  tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_256_GCM_SHA384',             keyAgreement: 'ML-KEM-1024', quantumSafe: true,  source: 'Network Scanner', lastScanned: '2026-02-25T14:36:00Z' },
  { id: 'e16', hostname: 'search-01.corp.local',            ipAddress: '10.90.2.30',     port: 9200, tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_128_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:37:00Z' },
  { id: 'e17', hostname: 'redis-01.corp.local',             ipAddress: '172.16.10.20',   port: 6379, tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:37:00Z' },
  { id: 'e18', hostname: 'monitoring-01.corp.local',        ipAddress: '172.16.5.80',    port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:38:00Z' },
  { id: 'e19', hostname: 'jenkins-01.corp.local',           ipAddress: '172.20.4.60',    port: 8443, tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_128_GCM',     keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:38:00Z' },
  { id: 'e20', hostname: 'auth-server-01.corp.local',       ipAddress: '172.30.5.50',    port: 443,  tlsVersion: 'TLS 1.3', cipherSuite: 'TLS_AES_256_GCM_SHA384',             keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:39:00Z' },
  { id: 'e21', hostname: 'cache-server-01.corp.local',      ipAddress: '172.40.8.100',   port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:39:00Z' },
  { id: 'e22', hostname: 'ldap-01.corp.local',              ipAddress: '192.168.1.100',  port: 636,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_CBC',      keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:40:00Z' },
  { id: 'e23', hostname: 'mail-01.corp.local',              ipAddress: '192.168.10.50',  port: 993,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_128_GCM',     keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:40:00Z' },
  { id: 'e24', hostname: 'crm-server-01.corp.local',        ipAddress: '192.168.150.75', port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'secp256r1',   quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:41:00Z' },
  { id: 'e25', hostname: 'api-gateway-01.corp.local',       ipAddress: '192.168.2.50',   port: 443,  tlsVersion: 'TLS 1.2', cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',     keyAgreement: 'x25519',      quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:41:00Z', certCommonName: 'API Gateway Primary' },
  { id: 'e26', hostname: 'cms-server-01.corp.local',        ipAddress: '192.168.200.10', port: 443,  tlsVersion: 'TLS 1.1', cipherSuite: 'TLS_RSA_WITH_AES_256_CBC_SHA256',     keyAgreement: 'RSA',         quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:42:00Z' },
  { id: 'e27', hostname: 'file-server-01.corp.local',       ipAddress: '192.168.50.20',  port: 445,  tlsVersion: 'TLS 1.1', cipherSuite: 'TLS_RSA_WITH_AES_128_CBC_SHA',        keyAgreement: 'RSA',         quantumSafe: false, source: 'Network Scanner', lastScanned: '2026-02-25T14:42:00Z' },
];

/* ═══════════════════════════════════════════════════════════════
   3. Software — DigiCert Software Trust Manager
   ═══════════════════════════════════════════════════════════════ */

export const SOFTWARE: DiscoverySoftware[] = [
  { id: 'sw1',  name: 'Production API Server',       version: '4.2.1',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '2048 bits', hashAlgorithm: 'SHA-256', cryptoLibraries: ['OpenSSL 1.1.1w'],                       quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-01-15', sbomLinked: true },
  { id: 'sw2',  name: 'Payment Processing Module',   version: '2.8.0',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '4096 bits', hashAlgorithm: 'SHA-384', cryptoLibraries: ['OpenSSL 3.2.0', 'libsodium 1.0.19'],    quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-02-01', sbomLinked: true },
  { id: 'sw3',  name: 'Mobile Banking App',          version: '6.1.3',  vendor: 'Internal',         signingAlgorithm: 'ECDSA', signingKeyLength: 'P-256',     hashAlgorithm: 'SHA-256', cryptoLibraries: ['BoringSSL'],                             quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-02-10', sbomLinked: false },
  { id: 'sw4',  name: 'PQC Migration Toolkit',       version: '1.0.0',  vendor: 'Internal',         signingAlgorithm: 'ML-DSA', signingKeyLength: '65 bytes', hashAlgorithm: 'SHA3-256', cryptoLibraries: ['liboqs 0.9.0', 'Bouncy Castle 1.77'],  quantumSafe: true,  source: 'DigiCert STM', releaseDate: '2026-02-20', sbomLinked: true },
  { id: 'sw5',  name: 'Infrastructure Agent',        version: '3.5.2',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '2048 bits', hashAlgorithm: 'SHA-256', cryptoLibraries: ['GnuTLS 3.8.2'],                         quantumSafe: false, source: 'DigiCert STM', releaseDate: '2025-12-05', sbomLinked: true },
  { id: 'sw6',  name: 'Secrets Rotation Service',    version: '2.1.0',  vendor: 'Internal',         signingAlgorithm: 'ECDSA', signingKeyLength: 'P-384',     hashAlgorithm: 'SHA-384', cryptoLibraries: ['wolfSSL 5.6.6'],                        quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-01-28', sbomLinked: false },
  { id: 'sw7',  name: 'Auth Gateway',                version: '5.0.1',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '2048 bits', hashAlgorithm: 'SHA-256', cryptoLibraries: ['NSS 3.95', 'Java Keytool 21.0.1'],      quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-01-10', sbomLinked: true },
  { id: 'sw8',  name: 'Quantum-Ready Notifier',      version: '1.2.0',  vendor: 'Internal',         signingAlgorithm: 'ML-DSA', signingKeyLength: '65 bytes', hashAlgorithm: 'SHA3-256', cryptoLibraries: ['liboqs 0.9.0'],                        quantumSafe: true,  source: 'DigiCert STM', releaseDate: '2026-02-18', sbomLinked: true },
  { id: 'sw9',  name: 'Data Pipeline Orchestrator',  version: '3.0.4',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '2048 bits', hashAlgorithm: 'SHA-256', cryptoLibraries: ['Go crypto 1.21.5'],                     quantumSafe: false, source: 'DigiCert STM', releaseDate: '2025-11-20', sbomLinked: false },
  { id: 'sw10', name: 'TLS Proxy Service',           version: '2.4.0',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '3072 bits', hashAlgorithm: 'SHA-256', cryptoLibraries: ['OpenSSL 3.2.0'],                        quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-02-05', sbomLinked: true },
  { id: 'sw11', name: 'Compliance Reporter',         version: '1.8.1',  vendor: 'Internal',         signingAlgorithm: 'RSA',   signingKeyLength: '2048 bits', hashAlgorithm: 'SHA-256', cryptoLibraries: ['Bouncy Castle 1.77'],                   quantumSafe: false, source: 'DigiCert STM', releaseDate: '2025-10-15', sbomLinked: true },
  { id: 'sw12', name: 'Container Runtime Security',  version: '4.1.0',  vendor: 'Internal',         signingAlgorithm: 'ECDSA', signingKeyLength: 'P-256',     hashAlgorithm: 'SHA-256', cryptoLibraries: ['OpenSSL 1.1.1w', 'libsodium 1.0.19'],   quantumSafe: false, source: 'DigiCert STM', releaseDate: '2026-01-22', sbomLinked: false },
];

/* ═══════════════════════════════════════════════════════════════
   4. Devices — DigiCert Device Trust Manager
   ═══════════════════════════════════════════════════════════════ */

export const DEVICES: DiscoveryDevice[] = [
  { id: 'd1',  deviceName: 'Industrial PLC Controller',    deviceType: 'PLC',             manufacturer: 'Siemens',       firmwareVersion: '4.2.1',  certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T08:00:00Z', source: 'DigiCert DTM' },
  { id: 'd2',  deviceName: 'Smart Meter Gateway',          deviceType: 'IoT Gateway',     manufacturer: 'Landis+Gyr',    firmwareVersion: '3.8.0',  certAlgorithm: 'ECDSA',  keyLength: 'P-256',     quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T07:45:00Z', source: 'DigiCert DTM' },
  { id: 'd3',  deviceName: 'Security Camera Array',        deviceType: 'IP Camera',       manufacturer: 'Axis',          firmwareVersion: '11.3.4', certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T09:15:00Z', source: 'DigiCert DTM' },
  { id: 'd4',  deviceName: 'Environmental Sensor Hub',     deviceType: 'Sensor',          manufacturer: 'Honeywell',     firmwareVersion: '2.1.0',  certAlgorithm: 'ECDSA',  keyLength: 'P-256',     quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-24T22:00:00Z', source: 'DigiCert DTM' },
  { id: 'd5',  deviceName: 'Badge Reader Main Entrance',   deviceType: 'Access Control',  manufacturer: 'HID Global',    firmwareVersion: '5.0.2',  certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T06:30:00Z', source: 'DigiCert DTM' },
  { id: 'd6',  deviceName: 'PQC Test IoT Node',            deviceType: 'IoT Node',        manufacturer: 'DigiCert Labs', firmwareVersion: '0.9.0',  certAlgorithm: 'ML-DSA', keyLength: '65 bytes',  quantumSafe: true,  enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T10:00:00Z', source: 'DigiCert DTM' },
  { id: 'd7',  deviceName: 'Fleet Tracker Module',         deviceType: 'GPS Tracker',     manufacturer: 'CalAmp',        firmwareVersion: '7.4.1',  certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T05:20:00Z', source: 'DigiCert DTM' },
  { id: 'd8',  deviceName: 'Medical Infusion Pump',        deviceType: 'Medical Device',  manufacturer: 'Baxter',        firmwareVersion: '3.2.5',  certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-24T18:00:00Z', source: 'DigiCert DTM' },
  { id: 'd9',  deviceName: 'HVAC Control Unit',            deviceType: 'Building Mgmt',   manufacturer: 'Johnson Controls', firmwareVersion: '6.0.3', certAlgorithm: 'ECDSA', keyLength: 'P-256',     quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T04:10:00Z', source: 'DigiCert DTM' },
  { id: 'd10', deviceName: 'Edge Compute Module',          deviceType: 'Edge Device',     manufacturer: 'NVIDIA',        firmwareVersion: '2.0.1',  certAlgorithm: 'ECDSA',  keyLength: 'P-384',     quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T11:00:00Z', source: 'DigiCert DTM' },
  { id: 'd11', deviceName: 'Robotic Arm Controller',       deviceType: 'Industrial Robot', manufacturer: 'FANUC',        firmwareVersion: '9.1.2',  certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Pending',  lastCheckin: '2026-02-20T14:00:00Z', source: 'DigiCert DTM' },
  { id: 'd12', deviceName: 'Quantum Gateway Device',       deviceType: 'Network Device',  manufacturer: 'DigiCert Labs', firmwareVersion: '1.0.0',  certAlgorithm: 'ML-KEM', keyLength: '768',       quantumSafe: true,  enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T12:00:00Z', source: 'DigiCert DTM' },
  { id: 'd13', deviceName: 'Power Grid Relay',             deviceType: 'SCADA',           manufacturer: 'ABB',           firmwareVersion: '4.5.0',  certAlgorithm: 'RSA',    keyLength: '2048 bits', quantumSafe: false, enrollmentStatus: 'Expired',  lastCheckin: '2025-11-10T08:00:00Z', source: 'DigiCert DTM' },
  { id: 'd14', deviceName: 'Warehouse Scanner',            deviceType: 'Barcode Scanner', manufacturer: 'Zebra',         firmwareVersion: '5.3.1',  certAlgorithm: 'RSA',    keyLength: '1024 bits', quantumSafe: false, enrollmentStatus: 'Enrolled', lastCheckin: '2026-02-25T03:00:00Z', source: 'DigiCert DTM' },
  { id: 'd15', deviceName: 'Smart Lock Entrance B',        deviceType: 'Access Control',  manufacturer: 'Assa Abloy',    firmwareVersion: '2.7.0',  certAlgorithm: 'ECDSA',  keyLength: 'P-256',     quantumSafe: false, enrollmentStatus: 'Revoked',  lastCheckin: '2026-01-05T12:00:00Z', source: 'DigiCert DTM' },
];

/* ═══════════════════════════════════════════════════════════════
   5. CBOM Imports — CycloneDX CBOM File Import
   ═══════════════════════════════════════════════════════════════ */

export const CBOM_IMPORTS: DiscoveryCbomImport[] = [
  { id: 'cb1',  fileName: 'payment-service-cbom.json',      format: 'CycloneDX JSON', specVersion: '1.6', totalComponents: 142, cryptoComponents: 38, quantumSafeComponents: 4,  nonQuantumSafeComponents: 26, conditionalComponents: 8,  importDate: '2026-02-20T09:00:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Payment Service' },
  { id: 'cb2',  fileName: 'auth-gateway-cbom.json',         format: 'CycloneDX JSON', specVersion: '1.6', totalComponents: 89,  cryptoComponents: 22, quantumSafeComponents: 2,  nonQuantumSafeComponents: 15, conditionalComponents: 5,  importDate: '2026-02-20T09:15:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Auth Gateway' },
  { id: 'cb3',  fileName: 'web-portal-cbom.json',           format: 'CycloneDX JSON', specVersion: '1.7', totalComponents: 215, cryptoComponents: 45, quantumSafeComponents: 6,  nonQuantumSafeComponents: 29, conditionalComponents: 10, importDate: '2026-02-21T11:00:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Web Portal' },
  { id: 'cb4',  fileName: 'mobile-app-cbom.xml',            format: 'CycloneDX XML',  specVersion: '1.6', totalComponents: 178, cryptoComponents: 31, quantumSafeComponents: 3,  nonQuantumSafeComponents: 22, conditionalComponents: 6,  importDate: '2026-02-21T14:30:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Mobile Banking App' },
  { id: 'cb5',  fileName: 'infra-agent-cbom.json',          format: 'CycloneDX JSON', specVersion: '1.6', totalComponents: 64,  cryptoComponents: 15, quantumSafeComponents: 0,  nonQuantumSafeComponents: 12, conditionalComponents: 3,  importDate: '2026-02-22T08:45:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Infrastructure Agent' },
  { id: 'cb6',  fileName: 'data-pipeline-cbom.json',        format: 'CycloneDX JSON', specVersion: '1.7', totalComponents: 312, cryptoComponents: 67, quantumSafeComponents: 8,  nonQuantumSafeComponents: 45, conditionalComponents: 14, importDate: '2026-02-22T15:00:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Data Pipeline' },
  { id: 'cb7',  fileName: 'pqc-toolkit-cbom.json',          format: 'CycloneDX JSON', specVersion: '1.7', totalComponents: 45,  cryptoComponents: 28, quantumSafeComponents: 24, nonQuantumSafeComponents: 1,  conditionalComponents: 3,  importDate: '2026-02-23T10:00:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'PQC Migration Toolkit' },
  { id: 'cb8',  fileName: 'container-security-cbom.json',   format: 'CycloneDX JSON', specVersion: '1.6', totalComponents: 98,  cryptoComponents: 19, quantumSafeComponents: 1,  nonQuantumSafeComponents: 14, conditionalComponents: 4,  importDate: '2026-02-23T16:30:00Z', status: 'Processing',  source: 'CBOM Import', applicationName: 'Container Security' },
  { id: 'cb9',  fileName: 'legacy-erp-cbom.xml',            format: 'CycloneDX XML',  specVersion: '1.6', totalComponents: 456, cryptoComponents: 82, quantumSafeComponents: 0,  nonQuantumSafeComponents: 75, conditionalComponents: 7,  importDate: '2026-02-24T09:00:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Legacy ERP System' },
  { id: 'cb10', fileName: 'secrets-service-cbom.json',      format: 'CycloneDX JSON', specVersion: '1.7', totalComponents: 72,  cryptoComponents: 35, quantumSafeComponents: 5,  nonQuantumSafeComponents: 21, conditionalComponents: 9,  importDate: '2026-02-24T14:00:00Z', status: 'Processed',   source: 'CBOM Import', applicationName: 'Secrets Service' },
  { id: 'cb11', fileName: 'compliance-reporter-cbom.json',  format: 'CycloneDX JSON', specVersion: '1.6', totalComponents: 55,  cryptoComponents: 12, quantumSafeComponents: 0,  nonQuantumSafeComponents: 10, conditionalComponents: 2,  importDate: '2026-02-25T08:00:00Z', status: 'Partial',     source: 'CBOM Import', applicationName: 'Compliance Reporter' },
  { id: 'cb12', fileName: 'broken-manifest.json',           format: 'CycloneDX JSON', specVersion: '1.6', totalComponents: 0,   cryptoComponents: 0,  quantumSafeComponents: 0,  nonQuantumSafeComponents: 0,  conditionalComponents: 0,  importDate: '2026-02-25T09:30:00Z', status: 'Failed',      source: 'CBOM Import', applicationName: 'Unknown' },
];
