/**
 * CrossRefPanel — Shared xBOM cross-reference view
 * Shows software ↔ crypto asset relationships
 */
import { useState, useMemo } from 'react';
import { Box, ShieldCheck, Link2 } from 'lucide-react';
import type { XBOMCrossReference, SBOMComponent, CryptoAsset } from '../../types';
import Pagination from '../Pagination';

interface Props {
  refs: XBOMCrossReference[];
  /** Optional: resolved software components to show better names */
  components?: SBOMComponent[];
  /** Optional: resolved crypto assets for richer display */
  cryptoAssets?: CryptoAsset[];
}

export default function CrossRefPanel({ refs, components, cryptoAssets }: Props) {
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);

  if (!refs.length) {
    return (
      <div style={{ padding: 32, textAlign: 'center', color: 'var(--dc1-text-muted)' }}>
        No cross-references found. Software ↔ crypto links will appear here when xBOM merge discovers relationships.
      </div>
    );
  }

  const resolveComponent = (ref: string) => {
    if (!components) return ref;
    const c = components.find(c => c['bom-ref'] === ref);
    return c ? `${c.group ? c.group + '/' : ''}${c.name}${c.version ? '@' + c.version : ''}` : ref;
  };

  const resolveCrypto = (ref: string) => {
    if (!cryptoAssets) return ref;
    const a = cryptoAssets.find(a => a.id === ref || a.name === ref);
    return a?.name ?? ref;
  };

  const paged = refs.slice((page - 1) * pageSize, page * pageSize);

  return (
    <>
      {/* Summary */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12, marginBottom: 16 }}>
        <div className="dc1-card" style={{ padding: 16, textAlign: 'center' }}>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#7c3aed' }}>{refs.length}</div>
          <div style={{ fontSize: 12, color: 'var(--dc1-text-muted)' }}>Cross-References</div>
        </div>
        <div className="dc1-card" style={{ padding: 16, textAlign: 'center' }}>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#1d4ed8' }}>{refs.reduce((s, r) => s + r.cryptoRefs.length, 0)}</div>
          <div style={{ fontSize: 12, color: 'var(--dc1-text-muted)' }}>Crypto Usages Mapped</div>
        </div>
      </div>

      {/* Cards */}
      <div className="dc1-card">
        <h3 style={{ margin: '0 0 12px', fontSize: 14, fontWeight: 600 }}>
          <Link2 size={15} style={{ marginRight: 6, verticalAlign: -2 }} />
          Software ↔ Crypto Mappings
        </h3>
        <p style={{ fontSize: 12, color: 'var(--dc1-text-muted)', marginBottom: 16 }}>
          These cross-references show which software components use which cryptographic assets — generated by the xBOM merge process.
        </p>
        {paged.map((cr, i) => (
          <div key={i} style={{ marginBottom: 12, padding: 12, borderRadius: 8, background: 'var(--dc1-bg-subtle, #f8fafc)', border: '1px solid var(--dc1-border)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
              <Box size={14} style={{ color: '#1d4ed8' }} />
              <span style={{ fontWeight: 600, fontSize: 13 }}>{resolveComponent(cr.softwareRef)}</span>
              <span style={{
                fontSize: 10, fontWeight: 500, padding: '1px 6px', borderRadius: 4,
                background: '#f1f5f9', color: '#64748b',
              }}>{cr.linkMethod}</span>
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, paddingLeft: 22 }}>
              {cr.cryptoRefs.map((ref, j) => (
                <span key={j} style={{
                  display: 'inline-flex', alignItems: 'center', gap: 4,
                  padding: '3px 10px', borderRadius: 6, fontSize: 11, fontWeight: 500,
                  background: '#f0e8ff', color: '#7c3aed', border: '1px solid #e8d5ff',
                }}>
                  <ShieldCheck size={11} />
                  {resolveCrypto(ref)}
                </span>
              ))}
            </div>
          </div>
        ))}
        <Pagination
          page={page}
          total={refs.length}
          pageSize={pageSize}
          onPageChange={setPage}
          onPageSizeChange={setPageSize}
        />
      </div>
    </>
  );
}
